version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # Раскомментируйте если используете PostgreSQL
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: