# Generated by Django 4.2.18 on 2025-02-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.CreateModel(
            name='PhotoCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_albom', models.PositiveSmallIntegerField(unique=True)),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albomphoto', to='photos.albom')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albomphoto', to='photos.photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='alboms',
            field=models.ManyToManyField(to='photos.albom', verbose_name='Список альбомов'),
        ),
    ]
