# Generated by Django 4.2.18 on 2025-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_albom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
