# Generated by Django 4.2.18 on 2025-02-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbomPhoto',
        ),
    ]
